sub_domains = [
    "www", "mail", "api", "dev", "test", "staging", "stage", "beta",
    "admin", "portal", "dashboard", "secure", "vpn", "cpanel", "webmail",
    "support", "help", "shop", "store", "blog", "static", "cdn",
    "img", "files", "assets", "app", "login", "sso", "internal",
    "server", "status", "billing", "chat", "gateway", "smtp", "vault",
    "news", "edge", "ftp", "panel", "reports", "jobs", "tickets",
    "proxy", "auth", "static1", "static2", "node1", "node2", "node3",
    "backup", "backup2", "alpha", "preview", "inventory", "payments",
    "alerts", "cdn2", "cdn3", "cdn-old", "auth2", "oauth", "oauth2",
    "public", "private", "monitor", "tracking", "kibana", "grafana",
    "mysql", "sql", "db", "db1", "db2", "mongodb", "redis", "cache",
    "cache2", "helpdesk", "jira", "confluence", "analytics", "insights",
    "app1", "app2", "mobile", "api2", "upload", "download", "ssh",
    "git", "gitlab", "jenkins", "ci", "cd", "builder", "orders",
    "customer", "user", "profile", "newsletter", "sandbox", "demo",
    "demo1", "pricing", "forum", "community", "partners", "cluster",
    "cluster1", "cluster2", "home", "live", "data", "root", "old",
    "legacy", "api-old", "main", "events", "event", "lambda",
    "cloud", "edge2", "v2", "v3", "v4", "backup-old", "login2",
    "admin2", "dmz", "radius", "sslvpn", "openvpn", "cas", "saml",
    "id", "identity", "user-api", "customer-api", "acp", "noc",
    "ops", "ops1", "ops2", "qa", "qa1", "qa2", "test-env",
    "staging-api", "payments-api", "secure-api", "gateway2",
    "firewall", "waf", "bastion", "proxy2", "reverse-proxy",
    "intranet", "intra", "hr", "finance", "accounting", "erp",
    "sap", "crm", "crm2", "dm", "docs", "doc", "media", "media2",
    "stream", "cdn-stream", "video", "videos", "img2", "cdn-img",
    "assets2", "cdn-assets", "static-cdn", "test-cdn", "auth-api",
    "login-api", "mobile-api", "node", "infra", "infra1", "infra2",
    "prod", "production", "preprod", "uat", "lab", "lab1", "lab2",
    "gateway-old", "edge-old", "internal-api", "private-api",
    "public-api", "public2", "mail2", "smtp2", "imap", "pop",
    "pop3", "calendar", "notes", "drive", "storage", "storage1",
    "sftp", "vpn2", "vpn-gateway", "mesh", "cluster-master",
    "cluster-worker", "k8s", "k8s1", "k8s-api", "docker",
    "registry", "container", "orchestrator", "loadbalancer",
    "lb", "lb1", "queue", "queues", "mq", "rabbitmq", "apache",
    "nginx", "iis", "nodejs", "python", "php", "java", "go"
]
